### ISSUE TITLE
Removal of pages

### ISSUE THREAD

**Issue by kristenmills** [rit-sse/alexandria#31]
Since I think we've all agreed that making the web app more patron oriented and having the windows 8 app be used on the surface, we need to discuss which views should be removed from the web app. 

Just for reference, the windows 8 app performs check outs, check ins, adding books, and viewing books. 

Because of this, I think we should remove:
- books#new
- checkouts#new
- checkouts#check_in (Only GET. We still need POST)

I think that's all that needs to be removed. Any other views I'm missing? Or any disagreement with the views that I suggested?

**Comment by nickserv** [comment]
This sounds good for now.
