### ISSUE TITLE
Active/Inactive strikes

### ISSUE THREAD

**Issue by kristenmills** [rit-sse/alexandria#32]
This way if we want to remove a strike for whatever reason (e.g. un banning a user), we can still keep the strike for historical data.

**Comment by nickserv** [comment]
If we want to keep this information around for historical data, why not use something like [paper trail](https://github.com/airblade/paper_trail) instead of having inactive strikes? Then you could actually delete the strike, but still have the history of it logged somewhere.

**Comment by kristenmills** [comment]
I don't want to delete them. I want a patron to be able to see all their strikes, not just their active strikes. With paper_trail, we can look up the data whenever we want but it's not visible all the time which is what I want.

**Comment by nickserv** [comment]
Ah, so you're saying there wouldn't be an easy way to look up all active/inactive strikes at once, and that's why we shouldn't use paper trail for this?

**Comment by kristenmills** [comment]
Yeah

**Comment by nickserv** [comment]
Alright, then I'm okay with active/inactive strikes.
